
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          # >>> REPLACE with YOUR Docker Hub image (Phase 4) <<<
          image: rahuldutta0487/hospital-app:1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: hospital-configmap
            - secretRef:
                name: hospital-secret
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  type: LoadBalancer
  selector:
    app: hospital-app
  ports:
    - port: 80
      targetPort: 5000
