# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: hospital-configmap
# data:
#   MONGO_URI: "mongodb://mongodb-service:27017/hospital_management"
#   PORT: "5000"
#   NODE_ENV: "production"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: hospital-secret
# type: Opaque
# stringData:                       # stringData = plain text, k8s encodes it for you
#   SESSION_SECRET: "CHANGE-ME-session-secret"
#   JWT_SECRET: "CHANGE-ME-jwt-secret"
#   ADMIN_USERNAME: "admin"
#   ADMIN_PASSWORD: "CHANGE-ME-strong-password"

apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-configmap
data:
  MONGO_URI: "mongodb://mongodb-service:27017/hospital_management"
  PORT: "5000"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
stringData:                       # stringData = plain text, k8s encodes it for you
  SESSION_SECRET: "CHANGE-ME-session-secret"
  JWT_SECRET: "CHANGE-ME-jwt-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "CHANGE-ME-strong-password"
