apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          envFrom:
            - configMapRef:
                name: hospital-configmap
            - secretRef:
                name: hospital-secret
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: hospital-app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}