apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-configmap
data:
  MONGO_URI: {{ .Values.config.MONGO_URI | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.secret.SESSION_SECRET | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
  ADMIN_USERNAME: {{ .Values.secret.ADMIN_USERNAME | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.ADMIN_PASSWORD | quote }}